Fix problems
Tech-Harbor/oranger_frontend pull request #55
Opened 2024-05-28 17:21 UTC by NazarBoychenko

2024-05-29 16:35 UTC, IvanRuskevych approved these changes
Назар, звертай увагу, що якщо надано якусь рекомендацію, то це не лише до того коду до якого прикріплено рекоменлація, але для перевірки скрізь у твоему коді, а також для використання у майбутньому.

2024-05-29 16:35 UTC, IvanRuskevych commented on src/components/Categories/Categories.jsx
> +    data: { getAllCategory: categoriesData } = { getAllCategory: [] },
Назар, потрібно перевірити запит на бекенд, оскільки в categoriesData повертає пустий масив:
Виникла помилка: Validation error (FieldUndefined@[getAllCategory/categoryName]) : Field 'categoryName' in type 'CategoryDTO' is undefined

2024-05-29 16:35 UTC, IvanRuskevych commented on src/components/Categories/Categories.jsx
Назар, якщо я правельно розумію то компонента Categories має відрендерити категорії товарів, які будуть існувати на сайті.
В мене була схожа задача, яв хедері робив випадаючий список з категоріями товарів.
Так от, оскільки список товарів це буде масив обєктів, то я створив тимчасово в constants/categories.js свій список, а поім використав його для того щоб написати верстку, де я імпортую цей список та через map() рендерю його .
Потім, коли цей список буде лежати на бекенді все що мені буде необхідно змінити, то це замість імпорту списку з папки constants, забрати цей список з беку. Розумієш? В мене код не зміниться, лише джерело звідки я буду забирати список розділів/категорій.
І ти собі зроби так само, наіщо ти множиш через for? а потім як? знову все переписувати? Адже тобі вже прийде список всіх розділів, а не один якийсь...
А запит той що ти зараз робиш через graphQL, залиш, просто виводь те що він надає в консоль, щоб ти бачив що запит повертається, що він працює. А коли буде створено на бекенді повноцінний список всіх розділів, тоді те що прийде з запиту підставиш в map().
Олексій ,я вважаю що так більш буде практично.

2024-05-29 16:35 UTC, IvanRuskevych commented on src/components/CardProduct/CardProduct.jsx
<i onClick={() => setToggle(!toggle)}>
тег <i> використовують для курсиву...
використай button

2024-05-29 16:35 UTC, IvanRuskevych commented on src/components/CardProduct/CardProduct.jsx
стилі необхідно винести в окремий файл

2024-05-29 16:35 UTC, IvanRuskevych commented on src/components/MainLayout/MainLayout.jsx
стилі в окремий файл

2024-05-29 16:35 UTC, IvanRuskevych commented on src/components/CardProduct/CardProduct.styled.js
якщо імпортуєш через index.js (як тут import { device } from '../../utils/index.js';) то не потрібно в кінці не потрібно прописувати /index.js

2024-05-29 16:35 UTC, IvanRuskevych commented on src/components/CardProduct/CardProduct.jsx
>  import PropTypes from 'prop-types';
Назар, в тебе імпорти не коректно відсортовані, подивись в моїх файлах, спочатку йдуть зовнішні, потім внутрішні, а вкінці стилі

2024-05-29 21:04 UTC, Aleksey2892 commented on src/components/Categories/Categories.jsx
exactly. Просто на той момент я не знав якої форми мають приходити дані з бека (я і зараз не знаю чи відомо якого формату дані будуть), а розмножити якось треба було. Якщо вже відома структура даних і є приклад хоча б для масива з 1 елементом - тоді це має сенс

2024-05-29 22:02 UTC, Aleksey2892 requested changes
waiting

2024-05-29 22:02 UTC, Aleksey2892 commented on src/components/Advertising/Advertising.jsx
> -import advertising from '../../assets/imges/Advertisement.jpg';
you rename advertisement to advertising. Again???

2024-05-29 22:02 UTC, Aleksey2892 commented on src/components/CardProduct/CardProduct.jsx
> +          <Image src={images[0]?.imageUrl} alt={name} />
If you already created ImageContainer - why do you use another one styled component "Image" inside??

2024-05-29 22:02 UTC, Aleksey2892 commented on src/pages/HomePage/HomePage.jsx
> -import { REQUESTS_FOR_PRODUCT_DATA } from '../../constants/requests.js';
if you use index.js file you should not use "/index.js" in the path string.

2024-05-30 23:22 UTC, IvanRuskevych requested changes
Request changes

2024-05-30 23:23 UTC, Aleksey2892 requested changes
waiting for changes

2024-06-01 15:16 UTC, IvanRuskevych requested changes

2024-06-01 15:16 UTC, IvanRuskevych commented on src/components/CardProduct/CardProduct.styled.js
>    ${fontStyles};
${fontStyles}; що це таке?
і в const Location те саме?

2024-06-01 15:16 UTC, IvanRuskevych commented on src/components/CardProduct/IconCustomStyles.js
що це за файл? ти дивився як у мене стилі прописані і де прописані?

2024-06-01 15:16 UTC, IvanRuskevych commented on src/components/Categories/Categories.styled.js
> +export const ImageContainer = styled.div`
Назар така ще від мене рекомендація на майбутнє: 
фронти мають негласне правило в якій послідовності ідуть стилі, ось як навчили мене:

  1) ...на початку саме головне, як і де розташовано елемент і що в ньому відбувається
// спочатку йде розташування типу position/top left тобто ти або хтось інший відразу бачить що це позиціонований компонент, це відразу дає представлення про компонент вцілому

// ... display... margin/padding... overflow так само дає представлення що відбувається з дочірніми елементами компонента...
// потім розміри w/h... border-radius...

2)...тепер менш важливе на що рідко звертаєш увагу, тобто скопіював з фігми і забувпро них)))
// кольори, тіні 
// шрифти

3) // і в кінці медіа правила в яких так само сортують все

Також, зазвичай між цими блоками роблять відступ для зручності, але от Олексій мені сказав при першому моєму пуші щоб я прибрав ці пропуски, ок я прибрав, це вже як то кажуть нюанси конкретного проєкту

  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  margin-bottom: 8px;

  height: 90px;

  border-radius: 50%;

  font-size: 10px;
`;

така структура дозволяє тобі самому швидше зорієнтуватися в стилях, особливо коли намагаєшся зрозуміти чому в тебе елемент рендериться не там де треба або коли потрібно щось змінити в розташуванні.

2024-06-01 15:16 UTC, IvanRuskevych commented on src/pages/HomePage/HomePage.jsx
> +import { REQUESTS_FOR_PRODUCT_DATA } from '../../constants/index.js';
у index.js ми робили реекспорт щоб спростити звернення до потрібних констант і для скорочення запису шляху, тому index.js видаляй в кінці '../../constants/index.js

2024-06-01 16:37 UTC, IvanRuskevych requested changes
ok

2024-06-17 13:42 UTC, Aleksey2892 approved these changes

2024-06-17 13:42 UTC, Aleksey2892 commented on src/components/SectionProduct/SectionProduct.jsx
> +        {!error && !loading && !cardProductData.length && <p>Немає оголошень, вийди розбійник</p>}
If you use the long conditions - you can create a special variable with these conditions before return and use it in JSX then

2024-06-17 13:42 UTC, merged